# Generated by Django 5.0.6 on 2026-03-22 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('teachers', 'Teachers Only'), ('students', 'Students Only'), ('admin', 'Admin Only')], default='all', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements appear at the top')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('target_class', models.ForeignKey(blank=True, help_text='Leave blank to broadcast school-wide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='academics.classroom')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
                'indexes': [models.Index(fields=['school', 'audience', '-published_at'], name='comms_annou_school__e14fb5_idx')],
            },
        ),
    ]
