# Generated by Django 5.0.6 on 2026-03-22 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('school_fees', 'School Fees'), ('development', 'Development Levy'), ('exam_fee', 'Exam Fee'), ('uniform', 'Uniform'), ('books', 'Books'), ('transport', 'Transport'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.term')),
            ],
            options={
                'ordering': ['class_room__name', 'fee_type'],
                'unique_together': {('school', 'class_room', 'term', 'fee_type')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('school_fees', 'School Fees'), ('development', 'Development Levy'), ('exam_fee', 'Exam Fee'), ('uniform', 'Uniform'), ('books', 'Books'), ('transport', 'Transport'), ('other', 'Other')], help_text='Copied from fee structure for quick reference', max_length=20)),
                ('amount_expected', models.DecimalField(decimal_places=2, help_text='Total fee owed', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance after this payment', max_digits=12)),
                ('receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online (Paystack)'), ('pos', 'POS'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=15)),
                ('payment_date', models.DateField()),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.feestructure')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.term')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'student', 'term'], name='finance_pay_school__1001e8_idx'), models.Index(fields=['receipt_number'], name='finance_pay_receipt_578993_idx')],
            },
        ),
    ]
